### ISSUE TITLE
Target debuff count is capped at 16 auras

### ISSUE THREAD

**Issue by Zyin055** [Aviana/LunaUnitFrames#868] opened 2021-06-23 02:17 UTC
When fighting Magtheridon today, I noticed the amount of debuffs displayed under the target frame was capped at 16 like in classic vanilla, but TBC has a higher debuff cap, resulting in some debuffs not being displayed.

**Comment by Aviana** [comment] 2021-06-24 08:23
Duplicate of #850. And already fixed.

**Closed by Aviana** 2021-06-24 08:23 UTC
