### ISSUE TITLE
Healcomm and Luna not working together

### ISSUE THREAD

**Issue by woopydalan** [Aviana/LunaUnitFrames#303] opened 2017-07-15 10:47 UTC
Hello,

When I have both Healcomm and Luna Unit Frames enabled, I get this error. Not sure what is going on
[2017/07/15 06:43:39-1]: modules\units.lua:487: bad argument #1 to `getn' (table expected, got nil)
<in C code>: in function `getn'
modules\units.lua:487: in function `Update'
modules\units.lua:772: in function `LoadRaidGroupHeader'
modules\units.lua:900: in function `InitializeFrame'
modules\units.lua:144: in function <Interface\AddOns\LunaUnitFrames\modules\units.lua:115>

  ---

**Comment by Aviana** [comment] 2017-07-22 14:02
Duplicate of #305

**Closed by Aviana** 2017-07-22 14:02 UTC
