### ISSUE TITLE
Pet frame bugging.

### ISSUE THREAD

**Issue by malkaviano** [Aviana/LunaUnitFrames#32] opened 2015-07-11 06:40 UTC
First time happened with my hunter, the pet frame got discolored.

It happened with my imp, frame is saying my imp is offline and it's by my side.

Happened after using the deep tram IF -> SW. Used the tram before. Hearthed, etc. Maybe a sporadic bug.

About 30m-1h gameplay session.

Screenshot: 
![luna](https://cloud.githubusercontent.com/assets/1530393/8632735/8359837c-277e-11e5-8471-976975121613.jpg)

**Comment by Aviana** [comment] 2015-08-15 20:16
This is caused by the server when events are firing incorrectly. I will switch pets from event driven to onupdate.

**Comment by Aviana** [comment] 2016-03-15 22:00
fixed in 2.0

**Closed by Aviana** 2016-03-15 22:00 UTC
Labels: bug
