### ISSUE TITLE
Bliz raid party frames disappear on reload

### ISSUE THREAD

**Issue by odd0** [Aviana/LunaUnitFrames#544] opened 2019-10-05 22:46 UTC
the bliz party raid frames disappear when you /reload and can't be turned back on unless you completely restart client. Disabling bliz frames and re-enabling luna frames for party shows no frames as well. 

I was using an older release that was working fine for a few weeks and invited a player to party today and bliz frames disappeared. Deleted luna folder and downloaded latest release and got my party frames back but they disappear on /reload. It seems luna party frames are not showing at all as well even after restarting client.

**Comment by Aviana** [comment] 2019-10-09 16:10
What are bliz party raid frames? Are you referring to the "new" default raid frames that you can also use in party? I can't see any issues with the default interface. Most of it gets disabled by default and if you activate it again it function normally for me after a /reload.

Older releases broke luna party settings when the frame they were anchored to was disabled. You can fix this by either starting with fresh setting or setting the "Anchor to" of the party to "none".

**Comment by Aviana** [comment] 2019-10-26 12:44
Well i can't reproduce any of this so i am closing this for now.

**Closed by Aviana** 2019-10-26 12:44 UTC
