### ISSUE TITLE
Borders/highlights options are not saved

### ISSUE THREAD

**Issue by d07RiV** [Aviana/LunaUnitFrames#538] opened 2019-09-30 18:36 UTC
After setting "on debuff" options in raid settings and doing /reload, the options show empty boxes again.

![image](https://user-images.githubusercontent.com/3448203/65906008-5b873f80-e3ca-11e9-9284-19a68ef5638d.png)

Moreover, is there a way to show Renew/Weakened Soul in raid frames somehow?

**Comment by Aviana** [comment] 2019-09-30 19:37
Duplicate of #519
Use squares / wait for aura revamp.

**Closed by Aviana** 2019-09-30 19:37 UTC

**Comment by d07RiV** [comment] 2019-10-01 11:38
Ah thanks, squares is what I was looking for. However, there seems to be no way to change font size on the timer, so if it's enabled it covers the whole square and more. Would be nice to have an option to make it smaller and/or disable timer text while keeping the "clock".

**Comment by Aviana** [comment] 2019-10-01 14:23
Disable the blizzard timers and use OmniCC.
