### ISSUE TITLE
Reckstacks.lua line 56 attempt to index field "background" (a nil value)

### ISSUE THREAD

**Issue by fourtwentycoding** [Aviana/LunaUnitFrames#528] opened 2019-09-27 16:59 UTC
As you can see below upon starting up the game and logging in I always receive this error.
![image](https://user-images.githubusercontent.com/55812270/65787152-4db19000-e126-11e9-9ad0-c31174990879.png)

I can replicate this error every time I log in.
Below is the full error message.
Date: 2019-09-27 12:55:50
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\LunaUnitFrames\modules\reckstacks.lua line 56:
   attempt to index field 'background' (a nil value)
Debug:
   ...terface\AddOns\LunaUnitFrames\modules\reckstacks.lua:56: ?()
   LunaUnitFrames\LunaUnitFrames.lua:92: FireModuleEvent()
   LunaUnitFrames\modules\layout.lua:123: Load()
   LunaUnitFrames\modules\units.lua:282: CheckModules()
   LunaUnitFrames\modules\units.lua:452:
      LunaUnitFrames\modules\units.lua:351
   [C]: SetAttribute()
   LunaUnitFrames\modules\units.lua:792: LoadUnit()
   LunaUnitFrames\modules\units.lua:1011: InitializeFrame()
   LunaUnitFrames\LunaUnitFrames.lua:226: LoadUnits()
   LunaUnitFrames\LunaUnitFrames.lua:40: OnInitialize()
   LunaUnitFrames\LunaUnitFrames.lua:265:
      LunaUnitFrames\LunaUnitFrames.lua:263
Locals:
self = <table> {
 OnDisable = <function> defined @Interface\AddOns\LunaUnitFrames\modules\reckstacks.lua:44
 moduleHasBar = true
 OnCombatlog = <function> defined @Interface\AddOns\LunaUnitFrames\modules\reckstacks.lua:98
 OnLayoutWidgets = <function> defined @Interface\AddOns\LunaUnitFrames\modules\reckstacks.lua:73
 CheckTalents = <function> defined @Interface\AddOns\LunaUnitFrames\modules\reckstacks.lua:85
 OnEnable = <function> defined @Interface\AddOns\LunaUnitFrames\modules\reckstacks.lua:7
 OnLayoutApplied = <function> defined @Interface\AddOns\LunaUnitFrames\modules\reckstacks.lua:48
 moduleKey = "reckStacks"
 moduleName = "Reckoning Stacks"
 Update = <function> defined @Interface\AddOns\LunaUnitFrames\modules\reckstacks.lua:113
}
frame = LUFUnitplayer {
 0 = <userdata>
 OnLeave = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:521
 UnregisterAll = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:137
 reckStacks = <unnamed> {
 }
 auras = <unnamed> {
 }
 registeredEvents = <table> {
 }
 UnitClassToken = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:533
 RegisterNormalEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:59
 topFrameLevel = 5
 RegisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:110
 SetBlockColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:183
 unitType = "player"
 SetRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:171
 visibility = <table> {
 }
 CheckModules = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:239
 indicators = <unnamed> {
 }
 unitInitialized = true
 unitRealType = "player"
 unit = "player"
 ReregisterUnitEvents = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:38
 RegisterUnitEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:104
 tagUpdate = <unnamed> {
 }
 fontstrings = <table> {
 }
 UnregisterSingleEvent = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:87
 DisableRangeAlpha = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:163
 highFrame = <unnamed> {
 }
 fullUpdates = <table> {
 }
 UnregisterUpdateFunc = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:127
 OnEnter = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:507
 BlizzRegisterUnitEvent = <function> defined =[C]:-1
 highlight = <unnamed> {
 }
 FullUpdate = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:30
 SetBarColor = <function> defined @Interface\AddOns\LunaUnitFrames\modules\units.lua:179
 borders = <unnamed> {
 }
}
reckStacks = <unnamed> {
 0 = <userdata>
 blocks = <table> {
 }
 fullSize = true
 PixelSnapDisabled = true
}
(for index) = 1
(for limit) = 4
(for step) = 1
id = 1
texture = <unnamed> {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'background' (a nil value)"

**Comment by Aviana** [comment] 2019-09-27 19:29
Duplicate of #520
Fix is in the next release (or current source).

**Closed by Aviana** 2019-09-27 19:29 UTC
