### ISSUE TITLE
Choose anchor point for frames

### ISSUE THREAD

**Issue by d07RiV** [Aviana/LunaUnitFrames#664] opened 2020-03-06 23:32 UTC
If I don't specify reference frame, the frame is positioned relative to some corner of the screen, so if my window size changes my whole UI goes out the window. Can we get an option to choose an attachment point, like left/top/center of screen etc? IIRC SUF had that option.

**Comment by Aviana** [comment] 2020-03-08 14:04
Duplicate of #601

**Closed by Aviana** 2020-03-08 14:04 UTC
