### ISSUE TITLE
Party frames still show in a raid despite setting not to

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [Aviana/LunaUnitFrames#792] opened 2020-11-30 04:18 UTC
See screenshot
![WoWScrnShot_112920_231724](https://user-images.githubusercontent.com/65634313/100568426-32499400-3299-11eb-9b37-1ac4af5c01bd.jpg)

**Comment by pedrorafaelpadilla** [comment] 2020-11-30 05:21
another oddity is that when I convert to a raid and back to a party, my party frames disappear even through a reload

**Comment by pedrorafaelpadilla** [comment] 2020-11-30 06:10
No lua errors through all of this, forgot to mention

**Comment by RobusXLR** [comment] 2020-12-03 11:18
I have the same issue. Party frames showing when in raid, even though option is turned off.

**Comment by Aviana** [comment] 2020-12-04 08:03
Duplicate of #783. The fix is already uploaded and will be in the next release.

**Comment by Aviana** [comment] 2020-12-05 00:34
Fixed in 4.040

**Closed by Aviana** 2020-12-05 00:34 UTC
