### ISSUE TITLE
Heal prediction frame of Prayer of healing(priest) does not work correctly

### ISSUE THREAD

**Issue by JudHyperion** [Aviana/LunaUnitFrames#597] opened 2019-11-11 07:12 UTC
Heal prediction frame of prayer of healing (Priest) does not work correctly

When priest casts prayer of healing, heal prediction frame shows only caster's frame, but does not show group member's health bar(heal prediction frame bar).

**Comment by Aviana** [comment] 2019-11-11 08:59
Duplicate of #593

**Closed by Aviana** 2019-11-11 08:59 UTC
