### ISSUE TITLE
Predictive healing bug and target of target flashing when hover casting over raid frames. 

### ISSUE THREAD

**Issue by Shaniquanda** [Aviana/LunaUnitFrames#315] opened 2017-10-06 06:52 UTC
So I downloaded the most recent version of luna because I wanted the reckoning stack counter and I am encountering this strange issue when I heal using hovercasting over the raid frames. I did delete the old luna info in saved variables as instructed when you use the new version of Luna. The video I will link shows it all. You can see that the predictive healing is showing up on me rather then the person I am actually healing, and you can also see that the target or target frame is flashing as I spam my healing button.

https://www.youtube.com/watch?v=_3hFK4hXryg&feature=youtu.be&ab_channel=jagon55

I think i will have to go back to the old version of luna for now. luckily i didnt empty my recycle bin so i still have it.

**Comment by Aviana** [comment] 2017-10-06 09:49
duplicate of #295

**Closed by Aviana** 2017-10-06 09:49 UTC
