### ISSUE TITLE
Ress indicator not working properly

### ISSUE THREAD

**Issue by llacczy** [Aviana/LunaUnitFrames#325] opened 2017-11-03 10:35 UTC
On the latest patch the resurrect indicator dont seems to show when im the one ressing, if other ppl from my raid resses someone then it shows. If i ress someone like 90% of the cases the indicator does not show up. Sometimes it does show.

**Comment by Aviana** [comment] 2017-11-03 11:08
Duplicate of #321

**Closed by Aviana** 2017-11-03 11:08 UTC
