### ISSUE TITLE
[Suggestion] The aggro square

### ISSUE THREAD

**Issue by sWxJaPkT** [Aviana/LunaUnitFrames#152] opened 2016-11-18 07:07 UTC
Love the addon. Amazing.

When a player  has aggro (in a raid/party) from a red square in their box to an outline in red over their box?As shown in screenshot - just did this in paint

http://i.imgur.com/C5vNdid.jpg

**Comment by zerosnake0** [comment] 2016-11-18 11:52
This is a duplicate of issue #115

**Closed** 2016-11-18 17:07 UTC
