### ISSUE TITLE
Add support for ClassicAuraDurations?

### ISSUE THREAD

**Issue by Loregon** [Aviana/LunaUnitFrames#567] opened 2019-10-20 20:26 UTC
Hi,

Can you make the addon compatible with ClassicAuraDurations? I would like to see the hidden auras and buffs that he allows you to see on standard frames. 
Thx

**Comment by Aviana** [comment] 2019-10-23 08:43
Duplicate of #540

**Closed by Aviana** 2019-10-23 08:43 UTC
